version: '3.7'

services:
  autoheal:
    image: willfarrell/autoheal
    restart: always
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  
  https-portal:
    image: steveltn/https-portal:1
    restart: always
    ports:
      - '80:80'
      - '443:443'
    logging:
      driver: syslog
      options:
        syslog-facility: daemon
        tag: docker_proxy/{{.Name}}/{{.ID}}
    environment:
      # STAGE: 'production' # Don't use production until staging works
      DOMAINS: >-
        ${STATIC_WEB_HOST} -> http://static,
        ${BACKEND_WEB_HOST} -> http://backend,
        ${FRONTEND_WEB_HOST} -> http://frontend,
      ERROR_LOG: stdout
      ACCESS_LOG: stderr
    volumes:
      - https-portal-data:/var/lib/https-portal
    networks:
      - backend
      - frontend
  db:
    image: mariadb:10.5.9
    restart: always
    container_name: db
    logging:
      driver: syslog
      options:
        syslog-facility: daemon
        tag: docker_db/{{.Name}}/{{.ID}}
    environment:
      TZ: Asia/Tokyo
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: mysqladmin -uroot -p${MYSQL_ROOT_PASSWORD} ping || exit 1
    networks:
      - backend
  frontend:
    build: ./frontend
    restart: always
    logging:
      driver: syslog
      options:
        syslog-facility: daemon
        tag: docker_frontend/{{.Name}}/{{.ID}}
    networks:
      - frontend
  static:
    image: nginx:latest
    restart: always
    healthcheck:
      test: curl --fail http://static/ || exit 1
    logging:
      driver: syslog
      options:
        syslog-facility: daemon
        tag: docker_static/{{.Name}}/{{.ID}}
    networks:
      - frontend
  backend:
    build: ./backend
    restart: always
    environment:
      TZ: Asia/Tokyo
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: curl --fail http://backend/ || exit 1
    logging:
      driver: syslog
      options:
        syslog-facility: daemon
        tag: docker_backend/{{.Name}}/{{.ID}}
    networks:
      - backend
volumes:
  db-data:
  https-portal-data: # Recommended, to avoid re-signing when upgrading HTTPS-PORTAL
  
networks:
  frontend:
  backend:
