version: '3.7'

services:
  autoheal:
    image: willfarrell/autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    logging:
      driver: syslog
      options:
        syslog-facility: daemon
        tag: docker_proxy/{{.Name}}/{{.ID}}
    environment:
      # STAGE: 'production' # Don't use production until staging works
      DOMAINS: >-
        ${STATIC_WEB_HOST} -> http://static,
        ${BACKEND_WEB_HOST} -> http://backend,
        ${FRONTEND_WEB_HOST} -> http://frontend,
      ERROR_LOG: stdout
      ACCESS_LOG: stderr
    volumes:
      - https-portal-data:/var/lib/https-portal
    # TODO: docker-compose -f docker-compose.yml --env-file .env config がリストにならないのでバグる
    #     : https://github.com/docker/compose/issues/7773
    # depends_on:
    #   - frontend
    #   - backend
    networks:
      - frontend
      - backend
  static:
    image: nginx:1.20.0
    logging:
      driver: syslog
      options:
        syslog-facility: daemon
        tag: docker_static/{{.Name}}/{{.ID}}
    healthcheck:
      test: curl --fail http://localhost/ || exit 1
    networks:
      - frontend
  frontend:
    image: frontend:latest
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
    logging:
      driver: syslog
      options:
        syslog-facility: daemon
        tag: docker_frontend/{{.Name}}/{{.ID}}
    healthcheck:
      test: curl --fail http://localhost/ || exit 1
    networks:
      - frontend
  backend:
    image: backend:latest
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
    environment:
      TZ: Asia/Tokyo
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: curl --fail http://localhost/ || exit 1
    logging:
      driver: syslog
      options:
        syslog-facility: daemon
        tag: docker_backend/{{.Name}}/{{.ID}}
    networks:
      - backend
  db:
    image: mariadb:10.5.9
    logging:
      driver: syslog
      options:
        syslog-facility: daemon
        tag: docker_db/{{.Name}}/{{.ID}}
    environment:
      TZ: Asia/Tokyo
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: test
    volumes:
      - db-data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/initizlize.sql:/docker-entrypoint-initdb.d/initizlize.sql
    healthcheck:
      test: mysqladmin -uroot -p${MYSQL_ROOT_PASSWORD} ping || exit 1
    networks:
      - backend
volumes:
  db-data:
  https-portal-data: # Recommended, to avoid re-signing when upgrading HTTPS-PORTAL

networks:
  frontend:
  backend:
